[package]
name = "neovide"
version = "0.1.0"
authors = ["keith <keith@the-simmons.net>"]
edition = "2018"
build = "build.rs"

[dependencies]
euclid = "0.20.7"
font-kit = "0.4.0"
skribo = { git = "https://github.com/linebender/skribo" }
lru = "0.4.3"
skulpin = "0.5"
derive-new = "0.5"
env_logger = "0.7.1"
#neovim-lib = { git = "https://github.com/daa84/neovim-lib", version = "0.6" }
rmpv = "0.4.2"
msgbox = "0.4.0"
rust-embed = { version = "5.2.0", features = ["debug-embed"] }
image = "0.22.3"
#nvim-rs = "0.1.0"
nvim-rs = { git = "https://github.com/KillTheMule/nvim-rs", branch = "futures", features = [ "use_tokio" ] }
tokio = { version = "0.2.9", features = [ "blocking", "process", "time" ] }
async-trait = "0.1.18"
lazy_static = "1.4.0"

[build-dependencies]
winres = "0.1.11"

[profile.release]
debug = true
