[package]
name = "neovide"
version = "0.1.0"
authors = ["keith <keith@the-simmons.net>"]
edition = "2018"

[dependencies]
euclid = "0.20.7"
font-kit = "0.4.0"
skribo = { git = "https://github.com/linebender/skribo" }
lru = "0.4.3"
skulpin = { path = "../skulpin" }
derive-new = "0.5"
env_logger = "0.7.1"
neovim-lib = { git = "https://github.com/daa84/neovim-lib", version = "0.6" }
rmpv = "0.4.2"
msgbox = "0.4.0"

[profile.release]
debug = true
